services:
  motivateme-database:
    container_name: motivateme-database
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: ${MOTIVATEME_BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${MOTIVATEME_BACKEND_DATABASE_PASSWORD}
      POSTGRES_DB: ${MOTIVATEME_BACKEND_DATABASE_NAME}
    ports:
      - 5432:5432
  motivateme-adminer:
    container_name: motivateme-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080