import dotenv from 'dotenv';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

dotenv.config({
  path: '../../.env',
});

const getValue = (name) => {
  return process.env[name] || '';
};

// Edit environment here!
const environment = {
  api: {
    baseUrl: getValue('MOTIVATEME_BACKEND_API_ENDPOINT')
  }
}

const environmentPath = `./src/environments`;
const environmentPathName = 'environments.ts';

const fileContent = `// Auto-Generated by apps/frontend/gen-env.js. Do not edit!
export const environment = ${JSON.stringify(environment)};
`;

mkdirSync(environmentPath, {
  recursive: true,
});

writeFileSync(join(environmentPath, environmentPathName), fileContent, {
  encoding: 'utf-8',
});